Imports

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

Load data and preview

In [ ]:
df = pd.read_csv('/Users/kaungkhantkyaw/Documents/GitHub/Analyse-US-Domestic-flights/Data/Raw/Origin_and_Destination_Survey_DB1BMarket_2025_1.csv')
display(df.head())
print(df.shape)

,ItinID,MktID,MktCoupons,Year,Quarter,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,Origin,OriginCountry,...,BulkFare,Passengers,MktFare,MktDistance,MktDistanceGroup,MktMilesFlown,NonStopMiles,ItinGeoType,MktGeoType,Unnamed: 41
0,202511660219,20251166021902,1,2025,1,14679,1467903,33570,SAN,US,...,0.0,1.0,351.5,1892.0,4,1892.0,1892.0,2,2,NaN
1,202511660220,20251166022001,1,2025,1,10397,1039707,30397,ATL,US,...,0.0,2.0,352.0,1892.0,4,1892.0,1892.0,2,2,NaN
2,202511660220,20251166022002,1,2025,1,14679,1467903,33570,SAN,US,...,0.0,2.0,352.0,1892.0,4,1892.0,1892.0,2,2,NaN
3,202511660221,20251166022101,1,2025,1,10397,1039707,30397,ATL,US,...,0.0,1.0,352.5,1892.0,4,1892.0,1892.0,2,2,NaN
4,202511660221,20251166022102,1,2025,1,14679,1467903,33570,SAN,US,...,0.0,1.0,352.5,1892.0,4,1892.0,1892.0,2,2,NaN

(7297028, 42)

Data Understanding

In [27]:
display(df.info())
display(df.describe())

<class 'pandas.DataFrame'>
RangeIndex: 7297028 entries, 0 to 7297027
Data columns (total 42 columns):
 #   Column              Dtype
---  ------              -----
 0   ItinID              int64
 1   MktID               int64
 2   MktCoupons          int64
 3   Year                int64
 4   Quarter             int64
 5   OriginAirportID     int64
 6   OriginAirportSeqID  int64
 7   OriginCityMarketID  int64
 8   Origin              str
 9   OriginCountry       str
 10  OriginStateFips     int64
 11  OriginState         str
 12  OriginStateName     str
 13  OriginWac           int64
 14  DestAirportID       int64
 15  DestAirportSeqID    int64
 16  DestCityMarketID    int64
 17  Dest                str
 18  DestCountry         str
 19  DestStateFips       int64
 20  DestState           str
 21  DestStateName       str
 22  DestWac             int64
 23  AirportGroup        str
 24  WacGroup            str
 25  TkCarrierChange     float64
 26  TkCarrierGroup      str
 27  OpCarrierChange     float64
 28  OpCarrierGroup      str
 29  RPCarrier           str
 30  TkCarrier           str
 31  OpCarrier           str
 32  BulkFare            float64
 33  Passengers          float64
 34  MktFare             float64
 35  MktDistance         float64
 36  MktDistanceGroup    int64
 37  MktMilesFlown       float64
 38  NonStopMiles        float64
 39  ItinGeoType         int64
 40  MktGeoType          int64
 41  Unnamed: 41         float64
dtypes: float64(9), int64(18), str(15)
memory usage: 2.7 GB

None

,ItinID,MktID,MktCoupons,Year,Quarter,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginStateFips,OriginWac,...,BulkFare,Passengers,MktFare,MktDistance,MktDistanceGroup,MktMilesFlown,NonStopMiles,ItinGeoType,MktGeoType,Unnamed: 41
count,7.297028e+06,7.297028e+06,7.297028e+06,7297028.0,7297028.0,7.297028e+06,7.297028e+06,7.297028e+06,7.297028e+06,7.297028e+06,...,7.297028e+06,7.297028e+06,7.297028e+06,7.297028e+06,7.297028e+06,7.297028e+06,7.297028e+06,7.297028e+06,7.297028e+06,0.0
mean,1.761292e+11,1.761292e+13,1.443969e+00,2025.0,1.0,1.286037e+04,1.286040e+06,3.200068e+04,2.679798e+01,5.440520e+01,...,7.030259e-05,1.885363e+00,2.768339e+02,1.304922e+03,3.109719e+00,1.302205e+03,1.226398e+03,1.925249e+00,1.925391e+00,NaN
std,6.468585e+10,6.468585e+12,5.438571e-01,0.0,0.0,1.533206e+03,1.533205e+05,1.381797e+03,1.718727e+01,2.726579e+01,...,8.384370e-03,4.856354e+00,2.328516e+02,8.196959e+02,1.669155e+00,8.184331e+02,7.767147e+02,2.629887e-01,2.627592e-01,NaN
min,2.025150e+07,2.025151e+09,1.000000e+00,2025.0,1.0,1.013500e+04,1.013506e+06,3.000900e+04,1.000000e+00,1.000000e+00,...,0.000000e+00,1.000000e+00,0.000000e+00,3.100000e+01,1.000000e+00,0.000000e+00,3.100000e+01,1.000000e+00,1.000000e+00,NaN
25%,2.025117e+11,2.025117e+13,1.000000e+00,2025.0,1.0,1.129800e+04,1.129806e+06,3.079200e+04,1.200000e+01,3.300000e+01,...,0.000000e+00,1.000000e+00,1.495000e+02,7.270000e+02,2.000000e+00,7.250000e+02,6.670000e+02,2.000000e+00,2.000000e+00,NaN
50%,2.025132e+11,2.025132e+13,1.000000e+00,2025.0,1.0,1.295300e+04,1.295304e+06,3.170300e+04,2.500000e+01,5.100000e+01,...,0.000000e+00,1.000000e+00,2.340000e+02,1.091000e+03,3.000000e+00,1.089000e+03,1.029000e+03,2.000000e+00,2.000000e+00,NaN
75%,2.025147e+11,2.025147e+13,2.000000e+00,2025.0,1.0,1.410700e+04,1.410702e+06,3.310500e+04,4.200000e+01,8.200000e+01,...,0.000000e+00,1.000000e+00,3.480000e+02,1.739000e+03,4.000000e+00,1.737000e+03,1.624000e+03,2.000000e+00,2.000000e+00,NaN
max,2.025160e+11,2.025160e+13,8.000000e+00,2025.0,1.0,1.686900e+04,1.686902e+06,3.610100e+04,7.800000e+01,9.300000e+01,...,1.000000e+00,1.032000e+03,3.065600e+04,1.134400e+04,2.300000e+01,1.134400e+04,9.411000e+03,2.000000e+00,2.000000e+00,NaN

In [30]:
display(df.dtypes.value_counts())
display(df.isna().sum())

int64      18
str        15
float64     9
Name: count, dtype: int64

ItinID                      0
MktID                       0
MktCoupons                  0
Year                        0
Quarter                     0
OriginAirportID             0
OriginAirportSeqID          0
OriginCityMarketID          0
Origin                      0
OriginCountry               0
OriginStateFips             0
OriginState                 0
OriginStateName             0
OriginWac                   0
DestAirportID               0
DestAirportSeqID            0
DestCityMarketID            0
Dest                        0
DestCountry                 0
DestStateFips               0
DestState                   0
DestStateName               0
DestWac                     0
AirportGroup                0
WacGroup                    0
TkCarrierChange             0
TkCarrierGroup              0
OpCarrierChange             0
OpCarrierGroup              0
RPCarrier                   0
TkCarrier                   0
OpCarrier                   0
BulkFare                    0
Passengers                  0
MktFare                     0
MktDistance                 0
MktDistanceGroup            0
MktMilesFlown               0
NonStopMiles                0
ItinGeoType                 0
MktGeoType                  0
Unnamed: 41           7297028
dtype: int64

In [31]:
df.duplicated().sum()

np.int64(0)

In [ ]:
display(df[['OriginState', 'OriginStateName']].drop_duplicates().sort_values(by='OriginState'))
display(df[['OriginState', 'OriginStateName']].nunique()) #checking if the origin state and origin state name are the same

       OriginState                                 OriginStateName
3253            AK                                          Alaska
17599           AL                                         Alabama
17565           AR                                        Arkansas
2004            AZ                                         Arizona
0               CA                                      California
1924            CO                                        Colorado
14558           CT                                     Connecticut
410379          DE                                        Delaware
1920            FL                                         Florida
1               GA                                         Georgia
677             HI                                          Hawaii
24257           IA                                            Iowa
895             ID                                           Idaho
3054            IL                                        Illinois
1910            IN                                         Indiana
1906            KS                                          Kansas
2626            KY                                        Kentucky
662             LA                                       Louisiana
4115            MA                                   Massachusetts
19022           MD                                        Maryland
16170           ME                                           Maine
13332           MI                                        Michigan
13368           MN                                       Minnesota
12589           MO                                        Missouri
2999            MS                                     Mississippi
9386            MT                                         Montana
2411            NC                                  North Carolina
28303           ND                                    North Dakota
21382           NE                                        Nebraska
90682           NH                                   New Hampshire
16136           NJ                                      New Jersey
17929           NM                                      New Mexico
824             NV                                          Nevada
1896            NY                                        New York
17447           OH                                            Ohio
2439            OK                                        Oklahoma
4136            OR                                          Oregon
9361            PA                                    Pennsylvania
669             PR                                     Puerto Rico
21793           RI                                    Rhode Island
1886            SC                                  South Carolina
17731           SD                                    South Dakota
2401            TN                                       Tennessee
88329           TT  U.S. Pacific Trust Territories and Possessions
1033            TX                                           Texas
885             UT                                            Utah
19227           VA                                        Virginia
8257            VI                             U.S. Virgin Islands
18969           VT                                         Vermont
834             WA                                      Washington
13366           WI                                       Wisconsin
19517           WV                                   West Virginia
886             WY                                         Wyoming

OriginState        53
OriginStateName    53
dtype: int64

In [ ]:
df.groupby('OriginState')[['OriginStateFips', 'OriginWac']].nunique().sort_values(['OriginStateFips', 'OriginWac'], ascending=False)
#this checks if the origin state fips and origin wac are the same and consistent with 1 state

             OriginStateFips  OriginWac
OriginState
AK                         1          1
AL                         1          1
AR                         1          1
AZ                         1          1
CA                         1          1
CO                         1          1
CT                         1          1
DE                         1          1
FL                         1          1
GA                         1          1
HI                         1          1
IA                         1          1
ID                         1          1
IL                         1          1
IN                         1          1
KS                         1          1
KY                         1          1
LA                         1          1
MA                         1          1
MD                         1          1
ME                         1          1
MI                         1          1
MN                         1          1
MO                         1          1
MS                         1          1
MT                         1          1
NC                         1          1
ND                         1          1
NE                         1          1
NH                         1          1
NJ                         1          1
NM                         1          1
NV                         1          1
NY                         1          1
OH                         1          1
OK                         1          1
OR                         1          1
PA                         1          1
PR                         1          1
RI                         1          1
SC                         1          1
SD                         1          1
TN                         1          1
TT                         1          1
TX                         1          1
UT                         1          1
VA                         1          1
VI                         1          1
VT                         1          1
WA                         1          1
WI                         1          1
WV                         1          1
WY                         1          1

In [ ]:
display(df['TkCarrierChange'].value_counts())
display(df['ItinGeoType'].value_counts())
display(df['MktGeoType'].value_counts())
#Checking the different value entries for these columns

TkCarrierChange
0.0    7185776
1.0     111252
Name: count, dtype: int64

ItinGeoType
2    6751570
1     545458
Name: count, dtype: int64

MktGeoType
2    6752605
1     544423
Name: count, dtype: int64

In [ ]:
display(df.groupby("MktGeoType")[["OriginState", "DestState"]].value_counts().head(30))
#checking the different states related to the market geo type of 1 and 2. This shows that 1 is most likely non-mainland US

MktGeoType  OriginState  DestState
1           HI           CA           40150
            CA           HI           38551
            HI           HI           17105
            PR           FL           11776
            HI           WA           11393
            FL           PR           11200
            WA           HI           11041
            AK           AK            8785
            HI           TX            8387
            TX           HI            8130
            HI           OR            6683
            PR           NY            6634
            OR           HI            6552
            NV           HI            6436
            HI           NV            6306
            NY           PR            6182
            PR           TX            5511
            HI           CO            5403
                         AZ            5353
            TX           PR            5291
            CO           HI            5262
            AZ           HI            5150
            UT           HI            4691
            HI           FL            4686
                         UT            4663
                         IL            4524
            FL           HI            4486
            IL           HI            4345
            CA           AK            4195
            HI           MN            4078
Name: count, dtype: int64

In [52]:
df[df["MktGeoType"] == 1][["Origin", "OriginState", "Dest", "DestState"]].drop_duplicates().head(50)

      Origin OriginState Dest DestState
668      ATL          GA  SJU        PR
669      SJU          PR  ATL        GA
676      ATL          GA  HNL        HI
677      HNL          HI  ATL        GA
780      ATL          GA  LIH        HI
781      LIH          HI  ATL        GA
3221     ATL          GA  ANC        AK
3252     ATL          GA  FAI        AK
3253     FAI          AK  ATL        GA
3269     ANC          AK  ATL        GA
4293     ATL          GA  KOA        HI
4294     KOA          HI  ATL        GA
4335     HNL          HI  SLC        UT
4440     LIH          HI  SEA        WA
4478     ATL          GA  OGG        HI
4484     OGG          HI  ATL        GA
8242     ATL          GA  CPX        PR
8243     CPX          PR  ATL        GA
8249     SJU          PR  JFK        NY
8256     ATL          GA  STX        VI
8257     STX          VI  ATL        GA
13380    ATL          GA  STT        VI
13425    STT          VI  ATL        GA
17628    ATW          WI  OGG        HI
17629    OGG          HI  ATW        WI
17694    ATW          WI  SJU        PR
17695    SJU          PR  ATW        WI
17709    ATW          WI  STT        VI
17712    STT          VI  ATW        WI
17715    ATW          WI  STX        VI
17717    STX          VI  ATW        WI
17731    ATY          SD  FAI        AK
20381    AUS          TX  HNL        HI
20383    HNL          HI  AUS        TX
21363    AUS          TX  OGG        HI
21366    OGG          HI  AUS        TX
22278    AUS          TX  SJU        PR
22305    SJU          PR  AUS        TX
22449    AUS          TX  STT        VI
22462    STT          VI  AUS        TX
22489    AUS          TX  STX        VI
22496    STX          VI  AUS        TX
27008    AUS          TX  KOA        HI
27013    KOA          HI  AUS        TX
27047    AUS          TX  LIH        HI
27050    LIH          HI  AUS        TX
27931    AUS          TX  ANC        AK
27936    ANC          AK  AUS        TX
28542    HNL          HI  PNS        FL
28546    HNL          HI  STL        MO

In [ ]:
df[df["MktGeoType"] == 2][["Origin", "OriginState", "Dest", "DestState"]].drop_duplicates().head(50)
# this confirms that the market geo type of 2 is mainland US, these values will apply to ItinGeoType 1 and 2 too

     Origin OriginState Dest DestState
0       SAN          CA  ATL        GA
1       ATL          GA  SAN        CA
649     ATL          GA  ECP        FL
652     ATL          GA  JAN        MS
655     ATL          GA  MCO        FL
658     ATL          GA  MIA        FL
661     ATL          GA  MSY        LA
662     MSY          LA  ATL        GA
665     ATL          GA  SAV        GA
675     SAN          CA  BNA        TN
683     SAN          CA  JFK        NY
685     SAN          CA  DCA        VA
702     ATL          GA  LAX        CA
703     LAX          CA  ATL        GA
779     SAN          CA  DFW        TX
784     ATL          GA  PHX        AZ
785     ATL          GA  ONT        CA
786     ONT          CA  ATL        GA
823     ATL          GA  RNO        NV
824     RNO          NV  ATL        GA
831     ATL          GA  SBA        CA
832     SBA          CA  ATL        GA
833     ATL          GA  SEA        WA
834     SEA          WA  ATL        GA
847     ATL          GA  SFO        CA
848     SFO          CA  ATL        GA
863     ATL          GA  SJC        CA
864     SJC          CA  ATL        GA
867     ATL          GA  SLC        UT
880     SAN          CA  CMH        OH
881     ATL          GA  DEN        CO
885     SLC          UT  JAC        WY
886     JAC          WY  SLC        UT
887     SLC          UT  ATL        GA
894     ATL          GA  SUN        ID
895     SUN          ID  ATL        GA
896     ATL          GA  SNA        CA
897     SNA          CA  ATL        GA
909     SAN          CA  CID        IA
914     ATL          GA  SAT        TX
1033    SAT          TX  ATL        GA
1882    ATL          GA  BOS        MA
1885    ATL          GA  CAE        SC
1886    CAE          SC  ATL        GA
1889    ATL          GA  CSG        GA
1895    ATL          GA  LGA        NY
1896    LGA          NY  ATL        GA
1899    ATL          GA  FLL        FL
1902    ATL          GA  GSO        NC
1905    ATL          GA  ICT        KS

In [ ]:
display(df['TkCarrier'].value_counts())
display(df['RPCarrier'].value_counts())
display(df['OpCarrier'].value_counts())
#checking the values of the different carrier columns for any similarities

TkCarrier
AA    1667888
WN    1478889
DL    1440933
UA    1283482
AS     366874
NK     230989
F9     222814
G4     170105
B6     169156
99     111252
HA      63961
MX      53146
XP      20401
SY      12974
3M       3088
--        809
LF        104
KG         49
PR         22
9K         19
9X         18
QR         17
QF         10
BA          5
VC          4
FJ          3
RJ          3
SQ          3
AD          2
TP          1
CX          1
IB          1
AM          1
AY          1
ET          1
AC          1
LA          1
Name: count, dtype: int64

RPCarrier
WN    1484292
DL    1088782
AA    1052476
UA     916221
OO     494443
AS     256448
NK     230989
YX     225208
F9     222814
MQ     195974
OH     173484
B6     172341
G4     170105
9E     161463
QX      70010
PT      69800
HA      67569
YV      58604
MX      53146
C5      37611
G7      35805
ZW      20797
XP      20401
SY      13178
3M       5067
Name: count, dtype: int64

OpCarrier
WN    1478889
99    1184639
DL     961186
AA     857528
UA     797726
OO     253082
NK     230989
AS     230436
F9     222814
G4     170105
B6     167500
YX     167326
MQ      96747
OH      88152
9E      83373
HA      63508
MX      53146
QX      47849
YV      38604
PT      21736
XP      20401
G7      20019
C5      16704
SY      12974
ZW       5977
3M       4564
--        809
LF        104
9K         68
KG         49
9X         18
VC          4
TP          1
ET          1
Name: count, dtype: int64

Dropping uneccessary columns

In [72]:
df = df.drop(columns=['OriginCountry', 'DestCountry', 'OriginAirportSeqID', 'DestAirportSeqID', 'OriginStateName',
 'DestStateName', 'OriginStateFips', 'OriginWac', 'DestStateFips', 'DestWac', 'WacGroup', 'Unnamed: 41', 'AirportGroup', 'ItinGeoType', 'OriginAirportID', 
 'DestAirportID', 'OpCarrierGroup', 'TkCarrierGroup'], errors='ignore') #dropping as this analysis is only for US domestic flights
print(df.columns)

Index(['ItinID', 'MktID', 'MktCoupons', 'Year', 'Quarter',
       'OriginCityMarketID', 'Origin', 'OriginState', 'DestCityMarketID',
       'Dest', 'DestState', 'TkCarrierChange', 'OpCarrierChange', 'RPCarrier',
       'TkCarrier', 'OpCarrier', 'BulkFare', 'Passengers', 'MktFare',
       'MktDistance', 'MktDistanceGroup', 'MktMilesFlown', 'NonStopMiles',
       'MktGeoType'],
      dtype='str')

In [73]:
df.sample(10)

,ItinID,MktID,MktCoupons,Year,Quarter,OriginCityMarketID,Origin,OriginState,DestCityMarketID,Dest,...,TkCarrier,OpCarrier,BulkFare,Passengers,MktFare,MktDistance,MktDistanceGroup,MktMilesFlown,NonStopMiles,MktGeoType
5736788,202513258870,20251325887001,2,2025,1,30208,AGS,GA,33214,SAT,...,AA,99,0.0,1.0,185.0,1235.0,3,1235.0,1009.0,2
1804384,2025130187,202513018701,1,2025,1,31057,CLT,NC,31703,LGA,...,DL,9E,0.0,2.0,176.0,544.0,2,544.0,544.0,2
262141,202514550082,20251455008201,1,2025,1,30198,PIT,PA,30977,ORD,...,UA,UA,0.0,2.0,180.0,413.0,1,413.0,413.0,2
6740164,202512637467,20251263746703,2,2025,1,32575,LAX,CA,31454,MCO,...,F9,F9,0.0,1.0,86.4,2351.0,5,2351.0,2218.0,2
5532036,202512473288,20251247328801,1,2025,1,34614,SLC,UT,32575,LAX,...,DL,DL,0.0,3.0,133.0,590.0,2,590.0,590.0,2
3507167,202515042912,20251504291201,1,2025,1,30325,DEN,CO,33342,MKE,...,WN,WN,0.0,1.0,481.0,896.0,2,896.0,896.0,2
3968909,202511397070,20251139707001,1,2025,1,30721,BOS,MA,32211,LAS,...,B6,B6,0.0,4.0,215.0,2381.0,5,2381.0,2381.0,2
5647503,202513187814,20251318781401,1,2025,1,33198,MCI,MO,31454,MCO,...,NK,NK,0.0,1.0,192.0,1072.0,3,1072.0,1072.0,2
3344528,202513999217,20251399921702,1,2025,1,33244,MEM,TN,30325,DEN,...,UA,UA,0.0,2.0,316.0,872.0,2,872.0,872.0,2
64893,202511715573,20251171557303,2,2025,1,33667,ORF,VA,30713,BOI,...,DL,DL,0.0,1.0,521.0,2354.0,5,2354.0,2144.0,2

Validity & Outliers check

In [ ]:
df.isna().sum() #Totally no missing values after unanmed column was dropped

ItinID                0
MktID                 0
MktCoupons            0
Year                  0
Quarter               0
OriginCityMarketID    0
Origin                0
OriginState           0
DestCityMarketID      0
Dest                  0
DestState             0
TkCarrierChange       0
OpCarrierChange       0
RPCarrier             0
TkCarrier             0
OpCarrier             0
BulkFare              0
Passengers            0
MktFare               0
MktDistance           0
MktDistanceGroup      0
MktMilesFlown         0
NonStopMiles          0
MktGeoType            0
dtype: int64

In [86]:
display((df['MktFare']<=0).sum())
display((df['MktDistance']<=0).sum())
display((df['MktDistanceGroup']<=0).sum())
display((df['MktMilesFlown']<=0).sum())
display((df['NonStopMiles']<=0).sum())
display((df['MktGeoType']<=0).sum())
#checking for invalid values for these numeric columns

np.int64(6500)

np.int64(0)

np.int64(0)

np.int64(809)

np.int64(0)

np.int64(0)

In [95]:
display((df['TkCarrier'] == '-').sum())
display((df['RPCarrier'] == '--').sum())
display((df['OpCarrier'] == '--').sum())
#checking for invalid values for these carrier columns

np.int64(0)

np.int64(0)

np.int64(0)

MktFare and MktMilesFlown has invalid values, thus we will be filtering out the invalid vlaues

In [ ]:
df = df[df['MktFare']>0]
df = df[df['MktMilesFlown']>0]
display((df['MktFare']<=0).sum())
display((df['MktMilesFlown']<=0).sum())
#The 809 records of invalid values in MktMilesFlown 
# align with the 809 entries of the value'--' in TkCarrer and OpCarrier, thus we do not need to filter for TK and Op

np.int64(0)

np.int64(0)